### ISSUE TITLE
Question and Answer formatting

### ISSUE THREAD

**Issue by tmorrell** [caltechlibrary/mkpage#2]
Support rendering markdown content with question and answer formatting, similar to the Software and Data Carpentry template.  Questions are written in the markdown file as:

```text
> ## Headline
>
> Question Text
> 
> > ## Solution
> > 
> > Solution test
> >
> {: .solution}
{: .challenge}
```

https://raw.githubusercontent.com/datacarpentry/OpenRefine-ecology-lesson/gh-pages/_episodes/01-working-with-openrefine.md

They show up in the rendered content with nice formatting around the question text and with the solution collapsed.  

http://www.datacarpentry.org/OpenRefine-ecology-lesson/01-working-with-openrefine/#solution

We don't need to use the exact same formatting or setup, but the ability to highlight the questions and hide the solutions would be a nice feature addition.

**Comment by rsdoiel** [comment]
This would be really cool.  We'll need to either fork and extend the Markdown processor we're currently using (no small task) or add some pre-processing.  Not sure which is the best approach.

**Comment by rsdoiel** [comment]
Pandoc is now the engine in `mkpage`. We will track whatever Pandoc adds and supports.
